2018-06-26 22:04:46,687 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 22:04:46,706 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 103, in <module>
    main()
  File "start.py", line 67, in main
    check_login()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 15, in check_login
    col = Image.open("raidtimer.jpg")
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'raidtimer.jpg'
