2018-06-26 23:19:25,260 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 23:19:25,260 [        MainThread][   detect_text][    INFO] Check for Loginbutton - start ...
2018-06-26 23:19:25,542 [        MainThread][   detect_text][    INFO] Check for Loginbutton - finished...
2018-06-26 23:19:25,543 [        MainThread][   detect_text][    INFO] Check for Messagebox - start ...
2018-06-26 23:19:25,801 [        MainThread][   detect_text][    INFO] Found Messagebox - closing ...
2018-06-26 23:19:25,801 [        MainThread][   detect_text][    INFO] Check for Messagebox - finished...
2018-06-26 23:19:25,802 [        MainThread][   detect_text][    INFO] Check for Xbutton - start ...
2018-06-26 23:19:25,823 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 105, in <module>
    main()
  File "start.py", line 69, in main
    check_Xbutton()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 69, in check_Xbutton
    col.save('temp.jpg')
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 622, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG
