2018-06-26 23:25:11,288 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 23:25:11,288 [        MainThread][   detect_text][    INFO] Check for Loginbutton - start ...
2018-06-26 23:25:11,581 [        MainThread][   detect_text][    INFO] Check for Loginbutton - finished...
2018-06-26 23:25:11,582 [        MainThread][   detect_text][    INFO] Check for Messagebox - start ...
2018-06-26 23:25:11,921 [        MainThread][   detect_text][    INFO] Found Messagebox - closing ...
2018-06-26 23:25:11,922 [        MainThread][   detect_text][    INFO] Check for Messagebox - finished...
2018-06-26 23:25:11,922 [        MainThread][   detect_text][    INFO] Check for Xbutton - start ...
2018-06-26 23:25:11,943 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 105, in <module>
    main()
  File "start.py", line 69, in main
    check_Xbutton()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 67, in check_Xbutton
    col[x, y] = (255, 255, 255, 255)
TypeError: 'Image' object does not support item assignment
