2018-06-26 21:56:47,503 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 21:56:47,505 [        MainThread][       _legacy][    INFO] Starting factory <client.VNCDoToolFactory instance at 0x111eb7e60>
2018-06-26 21:56:47,914 [            VNCPic][       _legacy][    INFO] Using protocol version 3.800
2018-06-26 21:56:49,720 [            VNCPic][       _legacy][    INFO] Stopping factory <client.VNCDoToolFactory instance at 0x111eb7e60>
2018-06-26 21:56:49,721 [            VNCPic][       _legacy][    INFO] Main loop terminated.
2018-06-26 21:56:49,721 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 103, in <module>
    main()
  File "start.py", line 67, in main
    check_login()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 12, in check_login
    raidtimer = col[190:510, 700:800]
TypeError: 'PngImageFile' object has no attribute '__getitem__'
