2018-06-26 23:44:40,722 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 23:44:40,723 [        MainThread][       _legacy][    INFO] Starting factory <client.VNCDoToolFactory instance at 0x11109cdd0>
2018-06-26 23:44:40,962 [            VNCPic][       _legacy][    INFO] Using protocol version 3.800
2018-06-26 23:44:42,882 [        MainThread][   detect_text][    INFO] Check for Loginbutton - start ...
2018-06-26 23:44:43,177 [        MainThread][   detect_text][   ERROR] KK
2018-06-26 23:44:43,177 [        MainThread][   detect_text][    INFO] Check for Loginbutton - finished...
2018-06-26 23:44:43,177 [        MainThread][   detect_text][    INFO] Check for Messagebox - start ...
2018-06-26 23:44:43,525 [        MainThread][   detect_text][   ERROR] 
2018-06-26 23:44:43,526 [        MainThread][   detect_text][    INFO] Check for Messagebox - finished...
2018-06-26 23:44:43,526 [        MainThread][   detect_text][    INFO] Check for Xbutton - start ...
2018-06-26 23:44:43,541 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 105, in <module>
    main()
  File "start.py", line 69, in main
    check_Xbutton()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 55, in check_Xbutton
    cv2.imwrite("raidscreen.png", raidtimer2)
NameError: global name 'raidtimer2' is not defined
