2018-06-26 23:24:15,091 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 23:24:15,091 [        MainThread][   detect_text][    INFO] Check for Loginbutton - start ...
2018-06-26 23:24:15,518 [        MainThread][   detect_text][    INFO] Check for Loginbutton - finished...
2018-06-26 23:24:15,519 [        MainThread][   detect_text][    INFO] Check for Messagebox - start ...
2018-06-26 23:24:15,918 [        MainThread][   detect_text][    INFO] Found Messagebox - closing ...
2018-06-26 23:24:15,918 [        MainThread][   detect_text][    INFO] Check for Messagebox - finished...
2018-06-26 23:24:15,918 [        MainThread][   detect_text][    INFO] Check for Xbutton - start ...
2018-06-26 23:24:15,938 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 105, in <module>
    main()
  File "start.py", line 69, in main
    check_Xbutton()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 69, in check_Xbutton
    pix.save('temp.png')
AttributeError: 'PixelAccess' object has no attribute 'save'
