2018-06-26 22:41:09,061 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 22:41:09,063 [        MainThread][       _legacy][    INFO] Starting factory <client.VNCDoToolFactory instance at 0x10f771ab8>
2018-06-26 22:41:09,360 [            VNCPic][       _legacy][    INFO] Using protocol version 3.800
2018-06-26 22:41:11,588 [        MainThread][   detect_text][    INFO] Text:O. K.
2018-06-26 22:41:11,589 [        MainThread][   detect_text][    INFO] Loginbutton gefunden
2018-06-26 22:41:11,589 [        MainThread][       _legacy][    INFO] Starting factory <client.VNCDoToolFactory instance at 0x111d22cb0>
2018-06-26 22:41:11,774 [            VNCPic][       _legacy][    INFO] Using protocol version 3.800
2018-06-26 22:41:12,166 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 103, in <module>
    main()
  File "start.py", line 67, in main
    check_login()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/detect_text.py", line 28, in check_login
    clickVNC(750, 340)
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/getVNCPic.py", line 179, in clickVNC
    client1.mouseMove(x, y).mousePress('1')
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/client.py", line 199, in mousePress
    buttons = self.buttons | (1 << (button - 1))
TypeError: unsupported operand type(s) for -: 'str' and 'int'
