2018-06-26 21:33:12,069 [        MainThread][         start][    INFO] Starting TheRaidMap
2018-06-26 21:33:12,069 [        MainThread][         start][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "start.py", line 101, in <module>
    main()
  File "start.py", line 65, in main
    getVNCPic()
  File "/Users/fameitelhuber/Desktop/TheRaidMapper/getVNCPic.py", line 162, in getVNCPic
    server = args.vncip + ':' + args.vncscr + ':' + args.vncprt
TypeError: cannot concatenate 'str' and 'int' objects
